### ISSUE TITLE
[Feature Request]: Option to make players withdraw notes only in multiples of a specific value

### ISSUE THREAD

**Issue by ninjakitty844** [Kikisito/NFCNotes#10]
**Describe the solution you'd like**
When using this option, the withdraw command would only allow you to specify how much money to withdraw, and plugin automatically decides what amount of notes based on how much each note will be worth (which you can set with another option). This will allow, for example, forcing players to deal with ONLY $10 bills. Or instead maybe only $1 coins.

**Comment by Kikisito** [comment]
Hello! For this feature I would need to rewrite some code from the withdraw command but I think it should be easy. As I told you in the other request, I'm busy right now with some work from the university. I'll add it asap.

**Comment by Kikisito** [comment]
Now available
