### ISSUE TITLE
Make notes glow.

### ISSUE THREAD

**Issue by Lightwav3** [Kikisito/NFCNotes#12]
Hello! I was wondering if NFCNotes have the option to make a note glow. It's just a suggestion, I don't know if you guys have it I'm just asking.

**Comment by Kikisito** [comment]
Hi! What do you mean? Make the note glow when it is dropped?

**Comment by Lightwav3** [comment]
> Hi! What do you mean? Make the note glow when it is dropped?

Sorry, I'm new to Github and I only know how to comment and download. I don't spend time here that much.
So, glowing. Like it's enchanted but it's theres no enchantment book. Just glowing.

**Comment by Kikisito** [comment]
Oh, you mean the glint. I'll look into it!

**Comment by Lightwav3** [comment]
> Oh, you mean the glint. I'll look into it!

Yes! Haha, I guess "glow" was another word for it, but glint was it! Thank you! :D

**Comment by Lightwav3** [comment]
Hello again! Just asking, will you add the glint? You can add it if you don't want to, no worries. :)

**Comment by Kikisito** [comment]
Hi! I'll definitely add it. I just need some time as I'm doing my final exams. Sorry for the delay.

**Comment by Lightwav3** [comment]
> Hi! I'll definitely add it. I just need some time as I'm doing my final exams. Sorry for the delay.

Oh, I'm sorry. It's okay, take your time. I love your plugin! :D

**Comment by Kikisito** [comment]
Done in https://github.com/Kikisito/NFCNotes/commit/72771f3bd3ca453956ec7b8a8cbb965aca814222.

I'll release it today with some other features.


> > Hi! I'll definitely add it. I just need some time as I'm doing my final exams. Sorry for the delay.
> 
> Oh, I'm sorry. It's okay, take your time. I love your plugin! :D

Thanks for your kind words! 😊
