### ISSUE TITLE
Commands dont work

### ISSUE THREAD

**Issue by Enderman8016** [Kikisito/NFCNotes#13]
I uploaded the mod jar file to my paper minecraft 1.16.5 server and it doesnt work, any help please?

**Comment by Kikisito** [comment]
I don't have enough information about your issue. Is any error shown? Please, edit your post and follow the [issue template](https://github.com/Kikisito/NFCNotes/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=)

**Comment by Kikisito** [comment]
If no error is shown, are you sure the plugin is in the `plugins` folder?

**Comment by Kikisito** [comment]
Closing due to no response
