### ISSUE TITLE
If inventory is full, the paper will not drop the floor, money will not turn back.

### ISSUE THREAD

**Issue by TimmyYue** [Kikisito/NFCNotes#17]
**Describe the bug**
Like title

**To Reproduce**
1. Nfcnotes the lastedt version
2. Server version: Minecraft Java 1.20.2 version 
3.If inventory only one space and withdraw than 64 amount will happen 

**Expected behavior**
If inventory is full, paper can drop the floor or turn back money.

**Screenshots**

**Error Stacktrace**
No

**Additional context**
No

**Comment by TimmyYue** [comment]
Video: https://iiil.io/6SF8

**Comment by Kikisito** [comment]
Confirmed. Thanks for resubmitting with more details. Fixing asap.

**Comment by RICE0707** [comment]
> Confirmed. Thanks for resubmitting with more details. Fixing asap.

Is there any progress on this bug?

**Comment by Kikisito** [comment]
> > Confirmed. Thanks for resubmitting with more details. Fixing asap.
> 
> Is there any progress on this bug?

Sorry for the delay. Uploading the fix today.
