### ISSUE TITLE
Console Commands

### ISSUE THREAD

**Issue by Cromare** [Kikisito/NFCNotes#19]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Adding console commands for when you would like to give a note to a player. Perhaps something like this:
/cn create [issuer text] [$$$] [player] [amount]

**Describe alternatives you've considered**
Going into the source and adding this myself, will still do, but might be nice for those who can't code.

**Comment by Kikisito** [comment]
The /createnote command can already be executed by the console. Other commands as /withdraw and /count are player-exclusive, the console cannot withdraw or count its money as it doesn't have
