### ISSUE TITLE
CustomModelData

### ISSUE THREAD

**Issue by lavaman11** [Kikisito/NFCNotes#2]
int getCustomModelData()
Gets the custom model data that is set.
CustomModelData is an integer that may be associated client side with a custom item model.

Plugins should check that hasCustomModelData() returns true before calling this method.

Returns:
the localized name that is set

org.bukkit.inventory.meta

let me know if you have implant that feature
then the "banknotes" could have their own model

**Comment by Kikisito** [comment]
I don't really understand this. I guess you're suggesting to add custom model data to notes instead of checking if they have any of this data

**Comment by Kikisito** [comment]
Closed due to no response
