### ISSUE TITLE
CustomModelData feature

### ISSUE THREAD

**Issue by Llopeando** [Kikisito/NFCNotes#6]
**Is your feature request related to a problem? Please describe.**
We are actually making custom textures to our server, but NFCNotes does not have any option to specify the CustomModelData of an item so it can show the custom texture.

**Describe the solution you'd like**
An option in the config to be able to specify the CustomModelData of an item (for example; "custommodeldata_id: 2"), so you can take out NFCNotes with custom textures.

**Describe alternatives you've considered**
None.

**Comment by Kikisito** [comment]
The [notes.custom-model-data-integer setting](https://github.com/Kikisito/NFCNotes/blob/master/src/main/resources/config.yml#L36) should already work for this. If it doesn't work, please tell me

**Comment by Llopeando** [comment]
Oh, so should I add it to the config file (NFCNotes v2.3.0)?

**Comment by Kikisito** [comment]
Yes, it should work by just adding it

**Comment by Kikisito** [comment]
Closing the issue, the feature is already implemented
