### ISSUE TITLE
[Feature Request]: Redeem Sound

### ISSUE THREAD

**Issue by ninjakitty844** [Kikisito/NFCNotes#9]
**Is your feature request related to a problem? Please describe.**
No, I just think it would be a neat feature.

**Describe the solution you'd like**
It would be cool to have an option in the configuration file where I can set a sound that plays when you redeem money.

I use sunflowers as my notes which represent coins really well with their texture. The sound "block.chain.break" really sounds like a coin being stored, so i would like it to play with all of my redeems.

**Comment by Kikisito** [comment]
Hi. This is a good idea! I'll add it as soon as I can. At the moment I'm busy with some university tasks, sorry for any inconvenience.

**Comment by Kikisito** [comment]
Added in e08d1f433b6b090623e197c7be990a72c3b6f194. Releasing later today.
